In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.11.0+cpu


### Introduction to Tensors

In [7]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [9]:
scalar.item()

7

In [10]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
MATRIX.ndim

2

In [16]:
MATRIX[1]

tensor([ 9, 10])

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim

3

In [24]:
TENSOR.shape

torch.Size([1, 3, 3])

In [27]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [26]:
TENSOR[0][1]

tensor([3, 6, 9])

In [28]:
TENSOR[0][2][2]

tensor(5)

### Random Tensors

In [29]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1875, 0.4531, 0.7996, 0.4455],
        [0.1467, 0.1954, 0.7986, 0.4018],
        [0.3619, 0.6453, 0.1572, 0.6431]])

In [30]:
random_tensor.ndim

2

In [31]:
random_tensor.shape

torch.Size([3, 4])

In [33]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor

tensor([[[0.1386, 0.2749, 0.3863],
         [0.1676, 0.2346, 0.2538],
         [0.1834, 0.6453, 0.1914],
         ...,
         [0.2574, 0.9830, 0.8864],
         [0.7555, 0.6262, 0.4658],
         [0.2800, 0.7141, 0.1136]],

        [[0.1829, 0.9803, 0.5908],
         [0.5273, 0.4137, 0.8577],
         [0.1232, 0.2448, 0.0403],
         ...,
         [0.2968, 0.3323, 0.1152],
         [0.3236, 0.4416, 0.8449],
         [0.1090, 0.1639, 0.5820]],

        [[0.4687, 0.6798, 0.7331],
         [0.1832, 0.8582, 0.7758],
         [0.9299, 0.5067, 0.0230],
         ...,
         [0.1017, 0.2988, 0.6786],
         [0.1376, 0.8824, 0.3342],
         [0.8035, 0.0768, 0.3035]],

        ...,

        [[0.5199, 0.6442, 0.3572],
         [0.7624, 0.5792, 0.8606],
         [0.9318, 0.5918, 0.0844],
         ...,
         [0.2958, 0.7997, 0.2397],
         [0.7415, 0.7694, 0.5788],
         [0.2626, 0.5581, 0.5569]],

        [[0.7809, 0.0232, 0.7066],
         [0.1479, 0.4813, 0.5618],
         [0.

In [35]:
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [36]:
zero = torch.zeros(size=(3, 4))
zero

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
one = torch.ones(size=(3, 4))
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [38]:
one.dtype

torch.float32

### Use range

In [42]:
one_to_ten = torch.arange(start=1, end=11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
ten_zero = torch.zeros_like(input=one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])